config/routes.rb
RobotexDashboard::Application.routes.draw do
  resources :tasks

  resources :robots

  match "robots/state_of/:id"=>"robots#state_of"
  match "robots/state_edit/:id"=>"robots#state_edit"
   match "robots/state_edit_all/:id"=>"robots#state_edit_all"
 
  match "robots/state_update/:id"=>"robots#state_update"
  
  match "home/week/:id"=>"home#week"
  match "home/index"=>"home#index"
  
  match "robots/state_update_all/:id"=>"robots#state_update_all"
  
  
  get "home/index"
  root :to => "home#index"

  
  

end

app/models/robot.rb
class Robot < ActiveRecord::Base
  
  after_create :gen_weeks
  
  validates :name,  :presence => true,
  :length => { :minimum => 3 }
  
   has_many :states, :dependent => :destroy
  has_many :tasks, :through => :states
 
  def gen_weeks
    for task in Task.find(:all)
      for week_n in 36..48
        State.create(:robot_id=>self.id, :task_id=>task.id,:progress=>0, :week_no=>week_n)
      end
    end
    
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  
  belongs_to :task
  belongs_to :robot
  validates :progress, :inclusion => { :in => 0..1 }
  

  validates_numericality_of :progress
end

app/models/task.rb
class Task < ActiveRecord::Base
  after_create :add_state
   has_many :states, :dependent => :destroy
  has_many :robots, :through => :states
 
  def add_state
    for robot in Robot.find(:all)
      for week_n in 36..48
        s=State.new
        s.robot_id=robot.id
        s.task_id=self.id
        s.progress=0
        s.week_no=week_n
        s.save
        #State.create(:robot_id=>robot.id, :task_id=>self.id, :progress=>0, :week_no=>week_n)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:state]==nil then
      @week_no=Time.now.strftime('%W')
      @year_no=Time.now.strftime('%Y')
    elsif  
      @week_no=Time.now.strftime('%W')
      @year_no=Time.now.strftime('%Y')
      @week_no=params[:state][:week_no] if params[:state][:week_no]!="" 
      @year_no=params[:state][:year_no] if params[:state][:year_no]!=""
    end
    
    @tasks=Task.find(:all, :order=>"display_order")
    
    @robots =Robot.find(:all, :conditions=>["year=?", @year_no])
    
    @states=[]
    @tasks.each do |t|
      @states[t.id]=[]
    end
    @rob=[]
    @robots.each do |r|
      @rob[r.id]=0
    end
    states=State.find(:all, :conditions => ["week_no=?",@week_no])
    states.each do |s|
      @states[s.task.id][s.robot.id]=s.progress
      @rob[s.robot.id]+=s.progress if @rob[s.robot.id]!=nil
    end
    #@tasks=Task.find(:conditions => ["week_no == ?", 35 ], :include => :robot:all)
    
    @all_weeks=State.find( :all, :select => ' DISTINCT week_no' )
    #@states=State.find(:all, :conditions => ["week_no=? robot_id in ?",@week_n, robots])
  end
  
  def week
    @robot = Robot.find(:all)
    @tasks = Task.find(:all)
    @status = State.find(:all)
  end

  
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  # GET /robots
  # GET /robots.xml
  def index
    @robots = Robot.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @robots }
    end
  end

  def state_of
    @robot = Robot.find(params[:id])
    @tasks=Task.find(:all)
    @all_weeks=State.find( :all, :select => ' DISTINCT week_no' )
    if params[:n2dal]==nil     
     @week_is= Time.now.strftime('%W') 
    else
     @week_is= params[:n2dal][:week_no]
   end
  end
  
  def state_edit
    @state = State.find(params[:id])
    last_week=@state.week_no.to_i-1
    if last_week>34
      @last_state=State.find(:all, :conditions => {
        :robot_id => @state.robot_id, 
        :task_id=> @state.task_id, 
        :week_no=> last_week})
      else 
        @last_state =nil
    end
    @tasks=Task.find(:all)
  end
  
  def state_edit_all
    @robot=Robot.find(params[:id])
    if params[:week_no]==nil     
     @week_is= Time.now.strftime('%W') 
    else
     @week_is=params[:week_no]
    end
    @tasks=Task.find(:all)
  end

  def state_update
    @state=State.find(params[:id])
    if @state.update_attributes(params[:update])
      flash[:notice]="editing successful"
      redirect_to :action=>'state_of', :id=> @state.robot_id
    else 
      flash[:error]="value must be between 0 and 1"
      @tasks=Task.find(:all)
      @state = State.find(params[:id])
      render :action=>'state_edit', :id=>@state.id
    end
  end
  
  def state_update_all
    @states=params[:status_info]
    @progress=params[:update]
      i=0
      @states.each do |s|
        @st=State.find(s)
        @st.progress=@progress[i]
        i+=1
        @st.save
      end
      redirect_to :action=>'state_of', :id=> params[:id]
  end

  
  # GET /robots/1
  # GET /robots/1.xml
  def show
    @robot = Robot.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @robot }
    end
  end

  # GET /robots/new
  # GET /robots/new.xml
  def new
    @robot = Robot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @robot }
    end
  end

  # GET /robots/1/edit
  def edit
    @robot = Robot.find(params[:id])
  end

  # POST /robots
  # POST /robots.xml
  def create
    @robot = Robot.new(params[:robot])

    respond_to do |format|
      if @robot.save
        format.html { redirect_to(@robot, :notice => 'Robot was successfully created.') }
        format.xml  { render :xml => @robot, :status => :created, :location => @robot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @robot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /robots/1
  # PUT /robots/1.xml
  def update
    @robot = Robot.find(params[:id])

    respond_to do |format|
      if @robot.update_attributes(params[:robot])
        format.html { redirect_to(@robot, :notice => 'Robot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @robot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.xml
  def destroy
    @robot = Robot.find(params[:id])
    @robot.destroy

    respond_to do |format|
      format.html { redirect_to(robots_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
  #  @tasks = Task.all
  @tasks =Task.find(:all, :order=>'display_order ASC')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@task, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1>Robotex progress - Aasta <%=@year_no%>, Nädal  <%= @week_no %></h1>
<% 
  week_list=[] 
  @all_weeks.each do |s| 
    week_list << s.week_no 
  end 
%>





<% form_tag(:action=>'index') do %>
  <%= link_to "Robots", robots_path %> | <%= link_to "Tasks", tasks_path %> | <%= select(:state,:year_no, (2010..Time.now.strftime('%Y').to_i), {:prompt=>'Vali aasta...'} )%><%= select(:state,:week_no, week_list, {:prompt=>'Vali nädal ...'} )%>
  <%= submit_tag('Go') %>
<%end%>

<table border=1>
<tr>
  <th>Task</th>
    <% @robots.each do |robot| %>
      <th width="100px"><%= robot.name %></th>
    <% end %>
</tr>


<%i=0%>
<% @tasks.each do |task| %>
<% row_color=cycle("B7CED5","ffffff")%>
<tr style="background:#<%= row_color%>;">
<td><%=i=task.id%>. <%= task.name -%></td>
<%@robots.each do |r|%>
  <td><%=@states[task.id][r.id]%></td>
<%end%>

</tr>
<% end %>
<tr style="font-weight:bold;">
<td>Progress</td>
<%@robots.each do |r|%>
  <td><%=@rob[r.id]%> <%= "("<<((@rob[r.id]*100)/i).round(2).to_s<<"%)" if @rob[r.id]!=0%></td>
<%end%>
</tr>
</table>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RobotexDashboard</title>
  <%= stylesheet_link_tag "print", :media => "print"%>
  <%= stylesheet_link_tag "scaffold", :media=>"screen" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<p id="notice"><%=raw notice %></p>
<%= yield %>

</body>
</html>

app/views/robots/_form.html.erb
<%= form_for(@robot) do |f| %>
  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% @robot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :homepage %><br />
    <%= f.text_field :homepage %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing robot</h1>

<%= render 'form' %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', robots_path %>

app/views/robots/index.html.erb
<h1>Listing robots</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Homepage</th>
    <th>Content</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @robots.each do |robot| %>
  <tr>
    <td><%= robot.name %></td>
    <td><%= link_to(robot.homepage,robot.homepage) %></td>
    <td><%= robot.content %></td>
    <td><%= robot.year %></td>
    <td><%= link_to 'Show', robot %></td>
    <td><%= link_to('States', :controller=>'robots', :action=>'state_of', :id=>robot.id) %></td>
    <td><%= link_to 'Edit', edit_robot_path(robot) %></td>
    <td><%= link_to 'Destroy', robot, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Robot', new_robot_path %>
<%= link_to('Back to menu',:action=>'index', :controller=>'home') %>

app/views/robots/new.html.erb
<h1>New robot</h1>

<%= render 'form' %>

<%= link_to 'Back', robots_path %>

app/views/robots/show.html.erb
<p>
  <b>Name:</b>
  <%= @robot.name %>
</p>

<p>
  <b>Homepage:</b>
  <%= link_to(@robot.homepage, @robot.homepage) %>
</p>

<p>
  <b>Content:</b>
  <%= @robot.content %>
</p>

<p>
  <b>Year:</b>
  <%= @robot.year %>
</p>


<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>

app/views/robots/state_edit.html.erb
<h1>   
<% @tasks.each do |task| %>
  <%if task.id==@state.task_id %>
    <%= task.name %>
  <%end%>
<%end%>
</h1>

<%form_tag(:action=>'state_update', :id=>@state.id) do%>
  Robot: <%=Robot.find(@state.robot_id).name%>
  <br/>
  Progress <%= text_field(:update, :progress, :value=> @state.progress)%>
  <%if @last_state!=nil %>
     <% @last_state.each do |l| %>
       (Last week: <%=l.progress %>)
      <%end%>
  <%end%>
  <br/>
 <%=submit_tag('Edit')%>
<%end%>

<%= link_to('Back to states', :action=>'state_of', :id=>@state.robot_id)  %> 
<%= link_to('Back to robots',:action=>'index', :controller=>'robots') %>

app/views/robots/state_edit_all.html.erb
<h1>   
    <%= @robot.name %>
</h1>
<%#all_states=[]%>
Editing week: <%=@week_is%>
 <%last_week= @week_is.to_i-1%>
<%last_state=''%>
<%= form_tag(:action=>'state_update_all') do%>
<table>
<th>Task</th> 
<% if last_week>34 %><th style="color:#c0c0c0;">Last week</th> <%end%>
<th>week  <%=@week_is%></th>
  <% @robot.states.each do |state| %>
    
      <% if state.week_no.to_s==last_week.to_s %>
        <%last_state=state.progress%>
     <%end%>
      <% if state.week_no.to_s==@week_is %>
      <tr>
      <%#all_states<<state%>
          <% @tasks.each do |task| %>
            <%if task.id==state.task_id%>
            <td> <%=label_tag(task.name)%> </td>
            <% end %>
          <% end %>
       <% if last_week>34 %> <td style="color:#c0c0c0;"><%=last_state%></td><%end%>
          <td> <%= text_field_tag('update[]', 'progress[]' ,:value=>state.progress)  %>  </td>

<td> <%= text_field_tag('status_info[]', 'state[]' ,:value=>state.id, :class=>'hidden_field')  %>  </td>    
  </tr>
      <% end %>
  <% end %>

</table>
 <%=submit_tag('Edit')%>
<%end%>

  <% if last_week>34 %> 
<%= form_tag(:action=>'state_update_all') do%>
  <% @robot.states.each do |state| %>
    
      <% if state.week_no.to_s==last_week.to_s %>
        <%last_state=state.progress%>
     <%end%>
      <% if state.week_no.to_s==@week_is %>
          <td> <%= text_field_tag('update[]', 'progress[]' ,:value=>last_state, :class=>'hidden_field')  %>  </td>
<td> <%= text_field_tag('status_info[]', 'state[]' ,:value=>state.id, :class=>'hidden_field')  %>  </td>    
  </tr>
      <% end %>
  <% end %>
<%=label_tag('')%>
</table>
 <%=submit_tag('copy last week')%>
<%end%>
 <%end%>


<%= link_to('Back to states', :action=>'state_of', :id=>@robot.id)  %> 
<%= link_to('Back to robots',:action=>'index', :controller=>'robots') %>

app/views/robots/state_of.html.erb
<h1> States for '<%= @robot.name %>'</h1>

<% total_progress=0 
week_list=[]
total_points=0%>
<% @all_weeks.each do |s| %>
  <%week_list << s.week_no%>
  <%end%>

<table>
  <th>Task</th>
  <th>Progress</th>
  <th> <%= form_tag(:action=>'state_of', :id=>@robot.id) do%>
         <%= select(:n2dal, :week_no ,week_list, {:prompt=>'Viewing week:'+@week_is} )%>
         <%=submit_tag('Go')%>
      <%end%>
  </th>
    <% @robot.states.each do |state| %>
      <% if state.week_no.to_s==@week_is %>
           <tr>
          <% @tasks.each do |task| %>
            <%if task.id==state.task_id%>
              <td><%= task.name %> </td> 
            <% end %>
          <% end %>
         <td><%= state.progress %> </td> 
             <%total_progress+=state.progress if state.progress!=nil
            total_points+=1%>
         <td><%= link_to('Edit', :action=>'state_edit', :id=>state.id)  %> </td>
         </tr>
      <% end %>
  <% end %>
  <tr>
    <td style="text-align:right; padding-right:20px;">
      <b>Total:</b>
    </td> 
    <td>
    <%=total_progress%> <%='('<<((100*total_progress)/total_points).round(2).to_s<<'%)' if total_progress!=0%>
    </td>
    <td>
    <%= form_tag(:action=>'state_edit_all', :id=>@robot.id) do%>
      <%=hidden_field_tag(:week_no , @week_is )%>
      <%=submit_tag('Edit all')%>
   <%end%>
  </td>
  </tr>
</table>
<br/>


<%= link_to('Back to robots',:action=>'index', :controller=>'robots') %>
<%= link_to('Back to menu',:action=>'index', :controller=>'home') %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br />
    <%= f.text_field :display_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Display order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.display_order %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>
<%= link_to('Back to menu',:action=>'index', :controller=>'home') %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Display order:</b>
  <%= @task.display_order %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>